#!/bin/bash

# Keeping the user in loop until they enter a valid database name or typing 'exit' to return to the main menu
while :; do
    echo "Enter database name or type 'exit' to return to the main menu:"
    read DATABASE_NAME
    # Changing the DB name to uppercase to match it with the required DB
    DATABASE_NAME=$(echo "$DATABASE_NAME" | tr '[:lower:]' '[:upper:]')

    DATABASE_DIR="./$DATABASE_NAME"
    # Type 'exit' to return to the main menu
    if [ "${DATABASE_NAME,,}" == "exit" ]; then
        system.sh
        break
    # Deleting the database dir and its content
    elif [ -d $DATABASE_DIR ]; then
        rm -r $DATABASE_DIR
        echo "Database '$DATABASE_NAME' has been successfully deleted."
        break
    # Printing an error messege on entering an invalid DB name
    else
        echo "Database '$DATABASE_NAME' does not exist. Please enter a valid database name."
    fi
done

# Wating for the user to type 'exit' to return to the main menu
while :; do
    echo "Type 'exit' to return to the main menu:"
    read EXIT

    if [ "${EXIT,,}" == "exit" ]; then
        system.sh
        break
    fi
done